# -*- coding: utf-8 -*-
"""python project  7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10HE9nYk-pTJP6SR0PUmPyRYAeEbp-00R

COVID.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WgBvaTBpLHFDhkKQ2yoaEfig_KrOPJTB
"
"""

import pandas as pd
import numpy as np
import random
!pip install faker
from faker import Faker
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

fake = Faker()

countries = ['India', 'USA', 'UK', 'Brazil', 'Germany', 'France', 'Italy', 'China']

data = []

for i in range(500):
    date = fake.date_between(start_date='-2y', end_date='today')
    country = random.choice(countries)

    confirmed = random.randint(1000, 100000)
    deaths = random.randint(10, 5000)
    recovered = random.randint(500, confirmed)

    active = confirmed - deaths - recovered

    data.append([date, country, confirmed, deaths, recovered, active])

df = pd.DataFrame(data, columns=[
    'Date', 'Country', 'Confirmed', 'Deaths', 'Recovered', 'Active'
])

df.head()

df['Date'] = pd.to_datetime(df['Date'])
df = df.sort_values(by='Date')
df.info()

print("Total Confirmed:", df['Confirmed'].sum())
print("Total Deaths:", df['Deaths'].sum())
print("Total Recovered:", df['Recovered'].sum())

trend = df.groupby('Date').sum()

plt.figure()
trend['Confirmed'].plot(color='skyblue', label='Confirmed Cases')
plt.title("COVID-19 Trend (Fake Data)")
plt.xlabel("Date")
plt.ylabel("Confirmed Cases")
plt.legend()
plt.grid(True)
plt.show()

top_countries = df.groupby('Country')['Confirmed'].sum().sort_values(ascending=False)

plt.figure(figsize=(10, 6))
sns.barplot(x=top_countries.index, y=top_countries.values, hue=top_countries.index, palette='viridis', legend=True)
plt.title("Top Countries by Confirmed Cases (Fake Data)")
plt.xlabel("Country")
plt.ylabel("Total Confirmed Cases")
plt.xticks(rotation=45, ha='right')
plt.show()

latest = df.groupby('Country')[['Confirmed', 'Deaths', 'Recovered', 'Active']].sum()

plt.figure(figsize=(10, 8))
plt.pie(latest['Confirmed'], autopct='%1.1f%%', startangle=140)
plt.title("Country Distribution")
plt.legend(latest.index, title="Countries", loc="center left", bbox_to_anchor=(1, 0, 0.5, 1))
plt.axis('equal')
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x=df['Confirmed'], y=df['Deaths'], hue=df['Country'], palette='tab10')
plt.title("Confirmed vs Deaths by Country")
plt.xlabel("Confirmed Cases")
plt.ylabel("Deaths")
plt.legend(title="Country")
plt.grid(True)
plt.show()

corr = df[['Confirmed', 'Deaths', 'Recovered', 'Active']].corr()

plt.figure(figsize=(8, 6))
sns.heatmap(corr, annot=True, cmap='coolwarm', cbar=True)
plt.title("Correlation Matrix")
plt.show()

fig = px.line(trend, x=trend.index, y='Confirmed', title='COVID Trend (Fake Data)')
fig.show()